version: '3.7'

services:

  ic-radio-server:
    image: ic-radio-server
    build:
      context: ./ic-radio-server
      dockerfile: Dockerfile
    expose:
      - 8081
    restart: always

  nginx:
    image: reverseproxy
    build:
      context: ./ic-radio-client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - ic-radio-server
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
