version: '3.7'

services:

  ic-radio-server:
    image: ic-radio-server
    build:
      context: ./ic-radio-server
      dockerfile: Dockerfile
    expose:
      - 8081
    restart: always

  reverseproxy:
    image: reverseproxy
    build:
      context: ./ic-radio-client
      dockerfile: Dockerfile
    ports:
    - 80:80
    depends_on: 
      - ic-radio-server
    restart: always

